services:
  php:
    image: php:8.2-fpm
    container_name: docu_php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./backend:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "9000:9000"
    depends_on:
      - db
    working_dir: /var/www/html

  db:
    image: mysql:8.0
    container_name: docu_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docu_mockup
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: docu_nginx
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ./frontend:/app
    command: npm run serve

volumes:
  db_data: